config/routes.rb
Rails.application.routes.draw do

root 'pages#home'  #This is the route for the homepage; using root makes the server immediately redirect to this page
get 'about', to: 'pages#about' #This is the about page
get 'readinglist', to: 'pages#readinglist'
get 'projects', to: 'pages#projects'
get 'playground', to: 'pages#playground'
get 'search_stocks', to: 'stocks#search'

resources :articles, except: [:signup] #this simple term resources allowed a:

get 'signup', to: 'users#signup'
resources :users, except: [:signup] #creates all routes except signup route

get 'login', to: 'sessions#login'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

resources :categories, except: [:destroy]
resources :posts, only: [:index]
resources :user_stocks, only: [:create, :destroy]

end

app/models/article.rb
#this is a model; with the magic of rails, just because this model exists, rails gives us getters and senders with the table in the db. 
class Article < ActiveRecord::Base #this is a subclass from ActiveRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 3, maximum: 100}    #this prevents an article from being submitted without a title; this helps maintain data integrity, also must be specific lengths
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController #class name has to be CamelCase

before_action :set_article, only: [:edit, :update, :show, :destroy] 
before_action :restrict, only: [:edit, :update, :new]
 
 
def index
  #@articles = Article.all
  @articles = Article.order("created_at desc") 
end


  def new   #it's called "new" because it's a new articles page
    @article = Article.new
  end
  

def edit
  
end
  
  
def create #this is for the process of sending an article to the database
  @article = Article.new(article_params) #This is the instance variable that will allow your article to be saved from the create method
  @article.user = User.last
  if @article.save
  flash[:notice] = "Article was successfully created"
  redirect_to article_path(@article)   #After creation, this will redirect the view to the last created article
  else
    render 'new'
  end
end


def update  
  if @article.update(article_params)
    flash[:notice] = "Article was successfully updated"
    redirect_to article_path(@article)
  else
    render 'edit'
  end
end


def show

end


def destroy
  @article.destroy
  flash[:notice] = "Article was successfully deleted"
  redirect_to articles_path
end


#THESE ARE METHODS THAT CAN BE USED THROUGHOUT THE CONTROLLER;
 private
  def set_article # This function used to be called in edit, show, update, and destroy; in efforts to shorten the code, we threw them all in one basket and called them at the top.
    @article = Article.find(params[:id])  #Find function to find the specific article in the db
  end
 
  def article_params
    params.require(:article).permit(:title, :description, category_ids:[])   #The params hash and the permissions will save the article title and description 
  end
  
  def restrict 
    if not logged_in?
      redirect_to root_path
    end
  end
  
end


 

app/views/articles/_article.html.erb
<!-- PARTIAL FOR INDEX OF ARTICLES -->
<div align="center" id="create-button"> 
      <% if logged_in? %>
        <%= link_to "Create New Article", new_article_path, class: "btn btn-lg btn-primary" %>
      <% else %>
        <%= nil %>
      <% end %>
      
      <%= link_to "Categories", categories_path, class: "btn btn-lg btn-primary" %>
    </div>
  <!-- Because there's |article| as the key, we have to refer to each article as (article) not (@article)-->
  
  <% obj.each do |article| %>
     <div class="row">
        <div id="article-index-div" class="col-xs-8">
          <div class= "well well-lg">
            <div class= "article-title">
              <%= link_to article.title, article_path(article) %>
            </div>
          
            <div class="article-teaser-body">
              <%= truncate(strip_tags(article.description), length: 280) %>
              
              <div class= "article-meta-details">
                <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
                       Last updated: <%= time_ago_in_words(article.updated_at) %> ago 
                </small>
            
             
           <div class="article-actions">
              <% if article.categories.any? %>
                <p> Categories: <%= render article.categories %> </p>
              <% end %>
              <% if logged_in? %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
              <%= link_to "Destroy", article_path(article), method: :delete,
              
                                          data: {confirm: "Are you sure you want to delete the article?"},
                                          class: "btn btn-xs btn-danger" %>
              <% else %>
            <%= nil %>
          <% end %>
              
                                          
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  </br>
  
  <% end %>

app/views/articles/_form.html.erb
<!-- ARTICLE FORM PARTIAL-->
<%= render 'shared/errors', obj: @article %>


<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :title %>
        </div>  
         
          <div class='col-sm-8'>
          <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
          </div>
      </div>
          

      
    <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :description %> 
        </div>
          <div class='col-sm-8'>
          <%= f.text_area :description, rows: 27, class: "form-control", placeholder: "Body" %>
          </div>
        </div> 
    
    
    <div class="form-group">
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>
      </div>
    </div>
          
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
    </div>
        
      
      <% end %>
      <div class="col-cs-4" align="center">
      <%= link_to "Cancel Request and Return to Articles Listing", articles_path %>
      </div>

  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center" id="page-header">Edit Existing Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<!-- ARTICLES INDEX-->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<h1 id="page-header" align="center">Today I Learned Blog</h1>
  
  <%= render 'article', obj: @articles %>
  
    

app/views/articles/new.html.erb
</br>
</br>

<h1 align="center" id="page-header">Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<!-- ARTICLE SHOW PAGE -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<div class="container-fluid">
  
    <div class="well col-xs-8" id="article-show-div">
      <h2 id="showpage-title" align="center"><%= @article.title %> </h2><hr>
        <%= simple_format(@article.description) %>
        <% if @article.categories.any? %>
          <p>Categories: <%= render @article.categories%></p>
        <% end %>
      
      <div class="article-actions">
        <% if logged_in? %>
        <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete this Article", article_path(@article), method: :delete,
            data: {confirm: "Are you sure you want to delete the article?"},
            class: "btn btn-xs btn-danger" %>
                                          
        <%= link_to "View all Articles", articles_path, class: "btn btn-xs btn-success"%>
        
        <% else %>
        <center><%= link_to "View all Articles", articles_path, class: "btn btn-xs btn-success"%></center>
        <% end %>
        
      </div>  
    </div>
</div>
  