config/routes.rb
Rails.application.routes.draw do

root 'pages#home'  #This is the route for the homepage; using root makes the server immediately redirect to this page
get 'about', to: 'pages#about' #This is the about page
get 'readinglist', to: 'pages#readinglist'
get 'projects', to: 'pages#projects'
get 'playground', to: 'pages#playground'
get 'search_stocks', to: 'stocks#search'

resources :articles, except: [:signup] #this simple term resources allowed a:

get 'signup', to: 'users#signup'
resources :users, except: [:signup] #creates all routes except signup route

get 'login', to: 'sessions#login'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

resources :categories, except: [:destroy]
resources :posts, only: [:index]
resources :user_stocks, only: [:create, :destroy]

end

app/views/pages/about.html.erb
<html>
<main role="main" id="about-page">
<div id="about-jumbo"class="jumbotron">
  <div class="container-fluid"></div>
</div>

<script src="https://cdn.jsdelivr.net/scrollreveal.js/3.3.1/scrollreveal.min.js"></script>
<h1 align="center" id="page-header" style="margin-bottom: 1cm;">My Story</h1>
<h2 align="center"> <%= image_tag("pins_journey.png", :alt => "journey") %> </h2>

<p id="secondary-text">I've worked in several different industries, and 
                      all of them have contributed to who I am today.</p>

<section id-"about-timeline" class="timeline">
  <div class="container">
    
    <div class="timeline-item">
      <div class="timeline-img"></div>
      <div class="timeline-content js--fadeInLeft">
        <h2><i id="fa-icon" class="fa fa-tree"></i> Tour Guide</h2>
        <div class="date">August 2013</div>
        <p>I became a Zipline Tour Guide at Historic Banning Mills during high school. Ironically I was afraid of heights when
            I first started; I just needed a job. Little did I know that this job would shape me into a good-willed, respectable, 
            and continually improving human being. I worked there for nearly five years.</p>
      </div>
    </div> 
    
    <div class="timeline-item">
      <div class="timeline-img"></div>
      <div class="timeline-content js--fadeInRight">
        <h2><i id="fa-icon" class="fa fa-graduation-cap"></i> Georgia Highlands College</h2>
        <div class="date">Sep 2014 - 2016</div>
        <p>Like many students, I was pressured into going to college right out of high school. I attended Georgia Highlands College
            with the intent of transferring to UGA, in pursuit of an economics degree. I didn't finish, not 
            because of grades, but because after two years I was told that I was advised incorrectly on what classes to take. 
            The college claimed I needed another year to complete a two year degree. This simply confirmed what I 
            already suspected: that college is mostly a scam and largely a waste of time. <b>I learned no marketable skills here, and I
            wish I had never attended college.</b></p>
      </div>
    </div> 
    
    <div class="timeline-item">
      <div class="timeline-img"></div>
      <div class="timeline-content js--fadeInLeft">
        <h2><i id="fa-icon" class="fa fa-code"></i> Self-Learning & Interest in Programming</h2>
        <div class="date">2015 - 2016</div>
        <p>Worried that I wasn't learning marketable skills in college, I supplemented it with my own personal learning curriculum.
            I first started taking classes on <a href="https://onemonth.com/">OneMonth.com</a> and completed courses in 
            <a href="https://onemonth.com/courses/pfnp"><b>HTML/CSS</b></a>,
            <a href="https://onemonth.com/courses/content-marketing"><b>Content Marketing</b></a>, and 
            <a href="https://onemonth.com/courses/growth-hacking"><b>Growth Hacking</b></a>. I discovered my interest in technology, 
            and built my first few websites, (which were very embarassing).  
            I discovered <a href="udemy.com">Udemy</a>, where I took classes in 
            <a href="https://www.udemy.com/javascript-from-beginner-to-expert-bring-life-to-your-site/learn/v4/overview">
            <b>Javascript</b></a>, 
            <a href="https://www.udemy.com/dc-level-1/"><b>Chinese</b></a>, and 
            <a href="https://www.udemy.com/the-complete-ruby-on-rails-developer-course/learn/v4/overview"><b>Ruby on Rails.</b></a>
            </p>
      </div>
    </div> 
  
    
    <div class="timeline-item">
      <div class="timeline-img"></div>
      <div class="timeline-content js--fadeInRight">
        <h2> <%= image_tag("alabama.png", :alt => "alabama") %> Guntersville Course Manager</h2>
        <div class="date">Apr 2016</div>
        <p>I was promoted to a Lead Tour Guide at Historic Banning Mills, and I was asked to help start up and temporarily 
        manage a zipline course in Guntersville Alabama, a small, rather beautiful mountain town. I helped 
        train the staff and train the local manager to be self-sufficient.   </p>
      </div>
    </div> 
    
    <div class="timeline-item">
      <div class="timeline-img"></div>
      <div class="timeline-content js--fadeInLeft">
        <h2><i id="fa-icon" class="material-icons">beach_access</i> Myrtle Beach Course Manager</h2>
        <div class="date">June - Aug 2016</div>
        <p>I was a temporary assistant manager at a course in Myrtle Beach South Carolina, a course Banning Mills had vested interests in. 
            Myrtle Beach is a challenging place; it's a town with one of the highest crime rates on the east coast. I helped train 
            the staff and trained a local manager to be self-sufficient. By the end of it, they wanted to hire me permanently, but 
            Myrtle Beach is different world. </p>
      </div>
    </div> 
    
    <div class="timeline-item">
      <div class="timeline-img"></div>
      <div class="timeline-content js--fadeInRight">
        <h2><%= image_tag("blue-sm-praxis.png", :alt => "praxis") %> Praxis</h2>
        <div class="date">May 2017</div>
        <p><a href="discoverpraxis.com">Praxis</a> is an organization that 
            connects driven, entrepreneurial-minded kids with startup companies to learn business skills through an  
            apprenticeship. Only 1% of applicants are accepted into the program, and luckily I passed. It was a great choice for me
            because I had no idea what I wanted to do with my life, and a startup is a place where I could wear many hats. 
            The program taught me, and continues to teach me, self-marketing skills and crucial business skills. 
            Companies like this are going to reinvent the education industry.</p>
      </div>
    </div> 
    
    <div class="timeline-item">
      <div class="timeline-img"></div>
      <div class="timeline-content js--fadeInLeft">
        <h2><i id="fa-icon" class="fa fa-building"></i> Khorus Software</h2>
        <div class="date">Aug 2017 - Feb 2018</div>
        <p>Praxis connected me with <a href="https://en.wikipedia.org/wiki/Joel_Trammell">Joel Trammell</a>
        , Founder of Khorus Software and current CEO of BlackBox Network Services. I read Joel's book, 
        <a href="https://www.amazon.com/CEO-Tightrope-Master-Balancing-Successful/dp/1626341060/ref=sr_1_1?s=books&ie=UTF8&qid=1515986582&sr=1-1&keywords=the+ceo+tightrope+by+joel+trammell">
        <i>The CEO Tightrope</i></a>, and agreed with his philosophy completely; I told Praxis that I absolutely wanted to work for Joel.
            I wore many hats, but I found myself migrating to programming. I helped design the pricing page for the Khorus website, and 
            I modified an <a href="https://gist.github.com/AlextheYounga/26faf858c673f2ceb1efd5574cfbc5fe">Excel macro</a>
            I found that helped increase our outbound marketing by 900%. This is when I learned I wanted to devote all my time to 
            development.
        </p>
      </div>
    </div> 
    
    <div class="timeline-item">
      <div class="timeline-img"></div>
      <div class="timeline-content js--fadeInRight">
        <h2><i id="fa-icon" class="fa fa-diamond"></i> Junior Ruby/Rails Developer</h2>
        <div class="date">Feb 2018</div>
        <p>I'm currently working as a freelance Ruby/Rails developer. Hire me if you're looking for beautiful HTML/CSS/Javascript
            design or looking to create a Ruby/Rails application.</p>
      </div>
    </div> 
    
    <div class="timeline-item">
      <div class="timeline-img"></div>
      <div class="timeline-content js--fadeInLeft">
        <h2> <i id="fa-icon" class="material-icons">landscape</i> Colorado Tour Guide</h2>
        <div class="date">Apr 2018</div>
        <p>I am currently living in Cañon City, Colorado and I am back to my roots as a Zipline Tour Guide at the Royal Gorge in Cañon City. Tour guide
            by day, developer by night. </p>
      </div>
    </div> 

  </div>
</section>
<%#= javascript_include_tag('timeline.js')%>

app/views/pages/blog.html.erb
</br>
<h1 id="page-header" align="center">The @AlextheYounger Blog</h1>
</br>
<main>
  <% @rss.items.each do |item|%>
    <div class="row">
      <div id="article-div" class="col-xs-8">
        <div class= "well well-lg">
          <div class= "article-title">
            <a href=<%="#{item.link}"%>> <%="#{item.title}"%></a>
          </div>
          
          <div class= "article-meta-details">
            <small>Created <%= time_ago_in_words "#{item.pubDate}"%> ago</small>
          </div>
        </div>  
      </div>
    </div>
  </br>
  <% end %>
    
    <center><a class="btn btn-xs btn-success" href="https://medium.com/@AlextheYounger/latest" role="button">
      View All Posts
    </a></center>
</main>

app/views/pages/home.html.erb
<html lang="en">
  <title>alextheyounger.com</title>
  
  <body>
    <div align="center" id="header" class="container-fluid">
      <img align="center" <%= image_tag("hammock_cutout - Copy.png", :alt => "hammock_cutout") %>
        <h1 class="display-3" id="name">Alex Younger</h1>
        <p align="center" id="header-sub">I build websites & applications and I write articles that make you question your existence.</p>
        <q id="header-sub"><i>It is what it is, and it's pretty good.</i></q> 
    </div> 
    <hr>
  
  
   <!-- BLOG -->
    
  <h1 align="center" style="margin-bottom: 20px;" id="section-header">Latest in: Today I Learned</h1>
  <div align="center"><%= link_to "View All", articles_path, class: "btn btn-lg btn-success" %></div></br>
   
  <%= if @articles.any? 
     then @articles.each do |article|%>
  
    <div class="row">
      <div class="col-xs-8" id="article-index-div">
        <div id="home-teaser-article" class= "well well-lg">
          <div class= "article-title">
            <%= link_to article.title, article_path(article) %>
          </div>
        
          <div class="article-teaser-body">
            <%= truncate(strip_tags(article.description), length: 280) %>  
            <!-- strip_tags removes HTML tags from description-->
          
          <div class= "article-meta-details">
              <small>Created<%#= article.user.username if article.user %>
                     <%= time_ago_in_words(article.created_at) %> ago, 
                     Last updated: <%= time_ago_in_words(article.updated_at) %> ago
              </small>
              <% if article.categories.any? %>
                <p> Categories: <%= render article.categories %> </p>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% end %>
<hr style="margin-top: 1.5cm;">
  


<!-- ABOUT -->

    <div style="margin-bottom: 1.5cm;">
      <center id="section-header" style="margin-bottom: 10px;">About Me</center>
        <img> <%= image_tag("roundheadshot - Copy.png", :alt => "roundheadshot", id: "headshot") %>
       
      
        <h2 class="col-xs-8" id="about-text">
          I'm Alex. I create/design websites and applications. My greatest strength is my love of learning, and my endless 
          curiosity that motivates me to learn everything I can. </br></br>
          
          I have a love for adventure, thrill and adrenaline. Programming is my day job. I ride ziplines by day.  
          </h2>
          </br>
        </br>
        <center><%= link_to "My Story", about_path, class: "btn btn-lg btn-primary" %></center>
    </div>
  <hr>
 


<!-- READING LIST-->
    <div class="container">
      <center><h1 style="margin-bottom: 20px;" id="section-header">Some of My Favorite Books</h1></center>
      <div class="row">
        <div class="col-md-12">
          <div class="carousel slide multi-item-carousel" id="theCarousel">
            <div class="carousel-inner">
             
              <div class="item active">
                <div class="col-xs-4"><a href="https://www.amazon.com/How-Win-Friends-Influence-People/dp/0671027034">
                  <img src="https://images-na.ssl-images-amazon.com/images/I/51X7dEUFgoL._SX320_BO1,204,203,200_.jpg" 
                  class="img-responsive"></a></div>
              </div>
              
              <div class="item">
                <div class="col-xs-4"><a href="https://www.amazon.com/How-Win-Friends-Influence-People/dp/0671027034">
                      <img src="https://images-na.ssl-images-amazon.com/images/I/51mZNhKc9iL._SX329_BO1,204,203,200_.jpg" 
                      class="img-responsive"></a></div>
              </div>
              
              <div class="item">
                <div class="col-xs-4"><a href="https://mises.org/library/foundations-morality">
                    <img src="https://mises.org/sites/default/files/styles/slideshow/public/static-page/img/The%20Foundations%20of%20Morality_Hazlitt_20120224_bookstore.jpg?itok=nSJi2ad4" 
                    class="img-responsive"></a></div>
              </div>
              
              <div class="item">
                <div class="col-xs-4"><a href="https://www.amazon.com/Antidote-Happiness-People-Positive-Thinking/dp/0865478015/ref=sr_1_1?s=books&ie=UTF8&qid=1515919681&sr=1-1&keywords=the+antidote+happiness+for+people+who+can%27t+stand+positive+thinking">
                    <img src="https://images.gr-assets.com/books/1389478401l/13721709.jpg" 
                    class="img-responsive"></a></div>
              </div>
              
              <div class="item">
                <div class="col-xs-4"><a href="https://www.amazon.com/Square-One-Foundations-Steve-Patterson-ebook/dp/B01M9JL27L/ref=sr_1_1?ie=UTF8&qid=1515980663&sr=8-1&keywords=square+one+steve+patterson">
                  <img src="https://images-na.ssl-images-amazon.com/images/I/414bcSvR7AL._SX326_BO1,204,203,200_.jpg" 
                  class="img-responsive"></a></div>
              </div>
              
              <div class="item">
                <div class="col-xs-4"><a href="https://mises.org/library/making-economic-sense">
                  <img src="https://mises.org/sites/default/files/styles/slideshow/public/static-page/img/Making%20Economic%20Sense_Rothbard.jpg?itok=LdvdFE5Y" 
                  class="img-responsive"></a></div>
              </div>
              
              <div class="item">
                <div class="col-xs-4"><a href="https://www.amazon.com/Good-Profit-Creating-Successful-Companies/dp/1101904135/ref=sr_1_1?s=books&ie=UTF8&qid=1515919796&sr=1-1&keywords=good+profit+charles+koch">
                  <img src="https://images-na.ssl-images-amazon.com/images/I/41ckVxWJzUL.jpg" 
                  class="img-responsive"></a></div>
              </div>
              
            </div>
            <a class="left carousel-control" href="#theCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
            <a class="right carousel-control" href="#theCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>
    
    <center style="margin: 30px;"><%= link_to "Full Reading List", readinglist_path, class: "btn btn-lg btn-primary" %></center>
  
  <%= javascript_include_tag('carousel.js')%>
  
</body>

<!--<a class="mtt" href="https://morningtrain.dk" target="_blank">
  	With <span>♥</span> from Alex Younger
</a>-->

app/views/pages/playground.html.erb
<h1 align="center" id="page-header">Playground</h1>
<p align="center" id="need-font" style="font-size: 18px;">
  A space for random, fun, interactive projects
</p>

<!-- halfway open book
<div id="project-box" 
      style="margin-bottom: 2cm; height: 270px">
  <div id="book" class="book">
    <div class="book-cover">
      <img <#%= image_tag("win_friends_influence.jpg", :alt => "Win Friends Influence People Open Book CSS", id: "book-img") %>
    </div>
  <div class="page"></div>
    <div class="page">
      <p>Be more concerned with your character than with your reputation, for your character is what you are, while your reputation 
        is merely what others think you are. It isn't what you have or who you are or where you are or what you are doing that makes 
        you happy or unhappy. It is what you think about it.</p>
    </div>
  </div>
</div>

<!-- end halfway open book -->

 <!--goal update tool -->
<div id="project-box" style="margin-bottom: 2cm;">
  <h3 id="need-font" align="center">Task Update Tool Proof of Concept</h3>
 <div id="goal-update">
   <form id="smileys">
    <div>How confident are you about completing this task on time?</div>
      <input type="radio" name="smiley" value="hopeless" class="hopeless">
    	<input type="radio" name="smiley" value="worrisome" class="worrisome">
    	<input type="radio" name="smiley" value="neutral" class="neutral">
    	<input type="radio" name="smiley" value="confident" class="confident" checked="checked">
    	<input type="radio" name="smiley" value="certain" class="certain">
    </form>
  </div>
  <div id="goal-update">
    <form id="smileys">
    <div>How do you feel about your current progress?</div>
      <input type="radio" name="smiley" value="hopeless" class="hopeless">
    	<input type="radio" name="smiley" value="worrisome" class="worrisome">
    	<input type="radio" name="smiley" value="neutral" class="neutral">
    	<input type="radio" name="smiley" value="confident" class="confident" checked="checked">
    	<input type="radio" name="smiley" value="certain" class="certain">
    </form>
  </div>
    
    <div id="question3">
      <p>Do you think this task needs reconsideration or updating?</p>
        <div style="padding-bottom: 1cm;">
          <button class="astext">Yes</button>
          <button class="astext" class="button active">No</button>
        </div>
    </div>
</div>

  <!-- end goal update -->
  <!-- stock lookup -->
<div id="project-box">
  <h3 align="center" id="need-font" style="margin-top: 1.5cm; font-size: 28px;">Search for Stocks</h3>
    <div>
      <%= form_tag search_stocks_path, remote: true, method: :get do %>
        <div id="stock-lookup" class="form-group row no-padding text-center col-md-10">
          <div class="col-md-8">
            <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: false,
                                        class: "form-control search-box input lg" %>
          </div>
          <div class="col-md-2">
            <%= button_tag(type: :submit, class: "btn btn-sm btn-success") do %>
              <i class="fa fa-search"></i> Search Stock Prices
            <% end %>
          </div>
          <% end %>
        </div>
      <div id="results">
        <%= render 'layouts/result' %>
      </div>
  </div>

  <!-- end stock-lookup -->
  
  <!-- watchlist -->
  <h3 align="center" id="need-font" style="margin-top: 2cm; font-size: 28px;">My Stock WatchList</h3>
  <%= render 'user_stocks/watchlist'%>
  <!-- end watchlist -->
</div>

  <!--map-->
  <div>
    <iframe id="map" src="https://www.google.com/maps/d/embed?mid=1xjnP9IvzZ5YARi0kVmI3FsPeLi7Yb0y9" 
    width="700" height="480"></iframe>
  </div>
  <!-- end map -->
  
  <!--quote generator-->
  <div id="quote-generator">
    <h2>My Favorite Quotes</h2>
      <div id="quoteContainer">
      <p></p>
    <p id="quoteGenius"></p>      
  </div><!--end quoteContainer-->
      
  <div id="buttonContainer">
      <a href="#" id="quoteButton">Quote Me</a>
  </div><!--end buttonContainer-->
</div><!--end quote generator-->
</div>

<script>
  document.getElementById('book').addEventListener('click', function() {
  this.classList.toggle('open');
});
</script>

<%#= javascript_include_tag('quote_generator.js')%>
<%#= javascript_include_tag('result.js')%>

app/views/pages/projects.html.erb
<h1 align="center" id="page-header" style="margin-bottom: 30px;">
  My Projects
</h1>

<div class"container-fluid" id="project-box">
  <h1 align="center" id="project-title">
    <a href="http://www.smartereverypage.com/">Smarter Every Page</a>
  </h1>
    <a href="http://www.smartereverypage.com/">
      <%=image_tag("smartereverypagelogo1.png", id: "project-banner", :alt=> "smarter every page") %>
    </a>
    <p id="project-text" align="center">I created this online book library to display the most sophisticated peices of literature for
                                        those who want to learn.</p>
</div>
</br>

<div class="container-fluid" id="project-box">
  <h1 align="center" id="project-title">
    <a href="https://mccarty-maintenance.herokuapp.com/">McCarty Maintenance & Mowing Website</a>
  </h1>
    <a href="https://mccarty-maintenance.herokuapp.com/">
      <%=image_tag("mccarty-mowing-project.png", id: "project-banner", :alt=> "mccarty banner") %>
    </a>
    <p id="project-text" align="center">I created this website for a client from the ground up in two weeks.</p>
</div>
</br>

<div class="container-fluid" id="project-box">
  <h1 align="center" id="project-title">
    <a href="http://www.alextheyounger.me/articles/68">Creating Your Own Stock Watchlist</a>
  </h1>
    <a href="http://www.alextheyounger.me/articles/68">
      <%=image_tag("watchlist_sm.png", id: "project-banner", :alt=> "watchlist banner") %>
    </a>
</div>
</br>

<div class="container-fluid" id="project-box">
  <h1 align="center" id="project-title">
    <a href="http://www.alextheyounger.me/articles/67">Creating Stock Price Lookup Using Stock_Quote Gem</a>
  </h1>
    <a href="http://www.alextheyounger.me/articles/67">
      <%=image_tag("stock_lookup_sm.png", id: "project-banner", :alt=> "stock_lookup_banner") %>
    </a>
</div>
</br>

<div class="container-fluid" id="project-box">
  <h1 align="center" id="project-title">
       <a href="http://www.alextheyounger.me/articles/20">Creating Your Own Medium.com API</a>
  </h1>
    <a href="http://www.alextheyounger.me/articles/20">
     <%= image_tag("medium_banner.png", id: "medium-banner", :alt => "medium_banner") %>
     </a>
   
</div>

<div class="container-fluid" id="project-box">
  <h1 align="center" id="project-title">
       <a href="tylermwllc.com">TylerMW LLC Photography Website</a>
  </h1>
    <a href="tylermwllc.com">
     <%= image_tag("tylermwllc_sm.png", id: "medium-banner", :alt => "tylermwllc.com") %>
     </a>
   
</div>