config/routes.rb
Rails.application.routes.draw do

root 'pages#home'  #This is the route for the homepage; using root makes the server immediately redirect to this page
get 'about', to: 'pages#about' #This is the about page
get 'readinglist', to: 'pages#readinglist'
get 'projects', to: 'pages#projects'
get 'playground', to: 'pages#playground'
get 'search_stocks', to: 'stocks#search'

resources :articles, except: [:signup] #this simple term resources allowed a:

get 'signup', to: 'users#signup'
resources :users, except: [:signup] #creates all routes except signup route

get 'login', to: 'sessions#login'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

resources :categories, except: [:destroy]
resources :posts, only: [:index]
resources :user_stocks, only: [:create, :destroy]

end

app/models/category.rb
#Model for Categories
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :restrict, only: [:new, :edit]
  
  def index
    @categories = Category.all
  end
  
  def create
    @category = Category.new(category_params)
      if @category.save
        flash[:success] = "Category was successfully created"
        redirect_to categories_path
      else
        render 'new'
      end
  end
  
  def new
    @category = Category.new
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Name was successfully updated"
      redirect_to categories_path(@category)
    else
      render 'edit'
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.order("created_at desc")
  end
  
  
  private
    def category_params
      params.require(:category).permit(:name)
    end
  
    def restrict 
      if not logged_in?
        redirect_to root_path
      end
    end
  
end

app/views/categories/_category.html.erb
<span class="badge">
  <%= link_to category.name, category_path(category) %> &nbsp;
</span>

app/views/categories/_form.html.erb
<!-- FORM FOR NEW AND EDIT CATEGORY -->
<%= render 'shared/errors', obj: @category %> <!-- Without initiation in categories_controller,
                                                    this will not work-->

</br>
</br>

    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :name %>
        </div>  
         
          <div class='col-sm-8'>
          <%= f.text_field :name, class: "form-control", placeholder: "Category Name", autofocus: true %>
          </div>
      </div>
          
        
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
          </div>
      </div>
     <% end %>
     
    <div class="col-cs-4" align="center">
    <%= link_to "Cancel Request and Return to Articles Listing", articles_path %>
    </div>

app/views/categories/edit.html.erb
<!-- Category Edit Page -->
<h1 align="center" id="page-header"> Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<!-- CATEGORIES INDEX -->

<h1 id="page-header" align="center">Today I Learned, In:</h1>


<% @categories.each do |category| %> <!-- Mind the %= -->
      <div class="row">
        <div id="category-div" class="col-xs-4">
          <div class= "well well-lg">
            <div class= "article-title">
              <%= link_to "#{category.name}", category_path(category) %>
            </div>
            <div align="center">
              <small><%= pluralize(category.articles.count, "article") %></small>
            </div>
            <div align="center" class="article-actions">
              <% if logged_in? %>
              <%= link_to "Edit Category Name", edit_category_path(category), class: "btn btn-xs btn-primary" %>
              <% else %>
            <%= nil %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </br>
<% end %>

<div class="col-cs-4" align="center">
    <%= link_to "Cancel Request and Return to Articles Listing", articles_path %>
</div>

app/views/categories/new.html.erb
<!-- NEW CATEGORY-->
<h1 align="center" id="page-header"> Create New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<!-- CATEGORY SHOW PAGE -->
<h1 align="center" id="page-header"> <%="Articles In: " + @category.name %> </h1>

<%= render 'articles/article', obj: @category_articles %>

</br><div align="center"><%= link_to "View All", articles_path, class: "btn btn-lg btn-success" %></div>