config/routes.rb
Rails.application.routes.draw do

root 'pages#home'  #This is the route for the homepage; using root makes the server immediately redirect to this page
get 'about', to: 'pages#about' #This is the about page
get 'readinglist', to: 'pages#readinglist'
get 'projects', to: 'pages#projects'
get 'playground', to: 'pages#playground'
get 'search_stocks', to: 'stocks#search'

resources :articles, except: [:signup] #this simple term resources allowed a:

get 'signup', to: 'users#signup'
resources :users, except: [:signup] #creates all routes except signup route

get 'login', to: 'sessions#login'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

resources :categories, except: [:destroy]
resources :posts, only: [:index]
resources :user_stocks, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<div id="footer-container" class="container">
  <footer align="center" class="footer">
    <small>
      Copyright &copy; <a href="alextheyounger.me">alexyounger.me</a> by Alex Younger. This site was built with Ruby on Rails.
    </small>
    <br/>
    
<div align="center" class="socialbtns">
<ul>
<li><a href="https://www.linkedin.com/in/alexyounger/" class="fa fa-lg fa-linkedin"></a></li>
<li><a href="https://www.facebook.com/alex.younger.7" class="fa fa-lg fa-facebook"></a></li>
<li><a href="https://github.com/AlextheYounga/alpha-blog" class="fa fa-lg fa-github"></a></li>
<li><a href="https://codepen.io/alextheyounger/" class="fa fa-lg fa-codepen"></a></li>
<li><a href="https://www.quora.com/profile/Alex-Younger-5" class="fa fa-lg fa-quora"></a></li>
<li><a href="https://medium.com/@AlextheYounger" class="fa fa-lg fa-medium"></a></li>
<li><a href="mailto:alexyounger07@gmail.com" class="fa fa-lg fa-envelope-o"></a></li>
<!-- <li><a href="https://www.quora.com/profile/Alex-Younger-5" class="fa fa-lg fa-quora"></a></li> -->
</ul>
</div>

  </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if flash[:danger]%>
    <ul class="alert alert-danger">                              
      <li id="error"><%= msg %></li>
    </ul>
  
  <% else %>
    <ul class="alert alert-success">                              
      <li id="success"><%= msg %></li>
    </ul>
  <% end %>
<% end %>
  

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-default navbar-fixed-top">
          <div class="navbar-header">
            <button id="navbar-button" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "HOME", root_path, class: "navbar-brand", id: "logo" %>
            
          </div>
          <div id="navbar" class="navbar-collapse collapse">
          
            <ul class="nav navbar-nav navbar-right" id="right-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
                role="button" aria-haspopup="true" aria-expanded="false">BLOGS<span class="caret"></span></a>
              <ul class="dropdown-menu" id="right-menu">
                <li><%= link_to "MEDIUM BLOG", posts_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "TODAY I LEARNED", articles_path  %></li>
              </ul>
              <li><%= link_to "ABOUT", about_path %></li>
              <li><%= link_to "READING LIST", readinglist_path %></li>
              <li><%= link_to "PROJECTS", projects_path %></li>
              <li style="margin-right: 10px;">
                  <%= link_to "PLAYGROUND", playground_path %></li>
              
              
              <li role="separator" class="divider"></li>
                <% if logged_in? %>
                  <li><%= link_to "LOG OUT", logout_path, method: :delete  %></li>
                <% else %>
                  <%= nil %>
                <% end %>
              </div>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/layouts/_result.html.erb
<% if @stock %>
    <div class="well results-block">
      <strong>Symbol: </strong><%= @stock.company_name%>
      <strong>Name: </strong><%= @stock.symbol%>
      <strong>Price: </strong><%= @stock.latest_price%>&nbsp;
      <% if logged_in? %>
        <%= link_to "Add to WatchList", user_stocks_path(user: current_user, stock_symbol: @stock.symbol),
                                                          class: "btn btn-xs btn-success", method: :post %>
      <% else %>
        <%= nil %>
    </div>
    <% end  %>
<% end %>
  
<% flash.each do |name, msg| %>
  <% if flash[:danger]%>
    <ul id="stock-danger" class="alert alert-danger">                              
      <li><%= msg %></li>
    </ul>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!--This is a wrapper file. Changes made to this page will render throughout every page of the app. Great place for navbar, ect. -->
<!DOCTYPE html>
<html>
<head>

  <title>alextheyounger.me</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  
  
  

</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %> <!-- This renders the messages partial all throughout the application --> 
  <%= yield %>  <!--This code allows this file to wrap all other views in the application -->



</body>

<footer>
  <%= render 'layouts/footer' %>
  <%#= debug(params) if Rails.env.development? %>
</footer>
</html>